# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory to /app
WORKDIR /MeteoApp/src/app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Expose port 5000 to the host machine
EXPOSE 5000

# Set the command to run the Flask application
CMD ["python3", "app.py"]