# Use an official Node.js runtime as a parent image
FROM node:17.9

# Set the working directory to /app
WORKDIR /MeteoApp/Front

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose port 8080 for the application to listen on
EXPOSE 8080

# Set the command to start the application
CMD [ "npm","run", "serve" ]